services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    command: python chapter_09/rest_api_with_aiohttp/main.py # tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "8080:8080"

volumes:
  postgres_data:
